server:
  port: 8081
  # port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: usuario-service
  config:
    import: optional:configserver:http://localhost:8085
#  profiles:
#    active: prod
  datasource:
    url: jdbc:mysql://localhost:3306/microservicios
    username: root
    password: 123456
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# Configuracion que expone informacion detallada del estado de salud de la aplicacion
management:
  health:
    circuitbreakers:
      enabled: true # 1. Activa la info de Circuit Breakers en el health check
    enpoints:
      web:
        exposure:
          include: health # 2. Expone el endpoint /actuator/health vía web
    endpoint:
      health:
        show-details: always # 3. Muestra detalles completos (no solo "UP" o "DOWN")

# Configuracion de Resilience4j
resilience4j:
  circuitbreaker:
    instances:
      usuarioServiceBreaker: # Debe coincidir con el name en @CircuitBreaker
        registerHealthIndicator: true # Exponer estado del breaker para monitoreo
        eventConsumerBufferSize: 10 # Tamaño del buffer para eventos (Logs internos)
        failureRateThreshold: 50 # Abrir si el 50% de las llamadas fallan
        minimumNumberOfCalls: 5 # Minimo de llamadas para calcular la tasa de fallos
        automaticTransitionFromOpenToHalfOpenEnabled: true # Pasa de ABIERTO a SEMI-ABIERTO automáticamente
        waitDurationInOpenState: 6s # Tiempo en OPEN antes de probar
        permittedNumberOfCallsInHalfOpenState: 3 # Pruebas en HALF_OPEN
        slidingWindowSize: 10 # Numero de llamadas para evaluar
        slidingWindowsType: COUNT_BASED # Configuracion basada en numero de llamadas

#eureka:
#  instance:
#    prefer-ip-address: true
#    # instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka